---
title: "Lesson 01 - Introduction to Digital Archives, with Trove as an example"
author: "Adela Sobotkova"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction


### What is this unit about?  
- This unit is about digital collections of cultural heritage and the techniques we use to create, describe, manage, use, and explore their content.
- The focus is on the intellectual, rather than physical, control. So not how we store things, but how we develop systems and standards to describe them.
- We’ll also be exploring the role of descriptive systems in supporting the discovery and use of collections. What can we do with them, particularly in the digital realm?

### What’s expected of you?
- To benefit from this unit you need to participate, ask questions, ask for help.
- We’ll work with you to complete a set of activities.

### What’s expected of us?
- We’ll document all the activities and make them available online 
- We’ll be available to assist students this week and in a series of follow-up face-to-face meetings

## Assessment
- Digital Archive review (comparative argumentative essay that builds on the skills developed in this week)

## Collectors and collections
### Introducing Trove
Let’s start our exploration of collections by looking at Trove, the principal public digital archive of Australia.

Why? Trove is one of the most modern and multi-faceted national digital archives out there in the world. It is a collection of collections – it brings together the holdings of hundreds of organisations, from local historical societies to national institutions. It’s a useful place to get an overview of Australia’s cultural heritage collections. But don’t be fooled into thinking that Trove includes everything! 

### Let’s try a simple search:

Go to www.trove.nla.gov.au
- Look around the page. What sorts of things are in Trove? How many resources are currently included? 
- Type ‘danish immigrant’ (without the quotes) in the search box and click ‘Search’.
- Find the ‘Pictures, photos, objects’ results box and click on it to focus on results from the Trove pictures zone. (There’s more about Trove’s zones here.)
- Let’s refine our results using facets. Under ‘Refine your results’ on the left hand side, click ‘Object’. What happens?
- Look through your results for a danish immigrant. How many can you find? Where do they [the records] come from?
- Click on the title of an object to view more details. Now click on the thumbnail or the ‘view at…’ link – Trove will send you to the website of the organisation that holds the object.

Write out brief answers to these questions and be ready to discuss:
1) how many resources are there in Trove?
2) what is a 'facet' and how does it differ from a Search box?
3) are records stored in Trove?

### Disasters and accidents

Let's say you are concerned about public health and industrialisation, and are interested in knowing the trend in the amount of accidents through the last 150 years, through time and space. 

Start a new search on www.trove.nla.gov.au
- Look around the page. What sorts of things are in Trove? How many resources are currently included? 
- Type ‘accident’ (without the quotes) in the search box and click ‘Search’.
- Find the ‘Digitised newspapers and more’ results box and click on it to focus on results from the Trove newspapers zone. (There’s more about Trove’s zones here.)
- Let’s refine our results using facets. Under ‘Refine your results’ on the left hand side, click ‘Decade’. What happens? Click for 'More'
- Look through your results for accidents reported in newspapers. How many can you find? Where do they [the records] come from?
- What decade sees the most accidents reported in Australia?
- How does the trend change in New South Wales versus Victoria?


### Are we all curators now?
Trove brings together cultural heritage collections, but it does more. It’s a place where individuals can create and contribute their own collections. For example, anyone can add their photos to Trove, simply by sharing them with the Australia in Pictures group on Flickr.

Do you share photos, links, or posts online? Do you create your own collections using tools such as Pinterest or Tumblr? The development of social media and a range of digital collecting tools has made it easier for us to find, organise and share things that are of interest to us.

Along the way, however, the word ‘curator’ has taken a bit of a battering. Read this short article – [‘All curators now’](/url https://www.1843magazine.com/content/ideas/anthony-gardner/all-curators-now) and watch this [video]():
As you can see, using Trove you explore collections all around Australia. For more search hints see the Trove help documentation.


Is there a difference between the sort of collecting that an individual undertakes and what happens in a museum or archive? What is that difference?

This is a question we’ll return to several times throughout this class. We’ll examine questions like authority and control – who chooses what is kept and why? We’ll also look at how collection items can be embedded within systems that document their context and relationships. What gives an object its meaning, significance, and authenticity?

Using Trove, people can assemble their own collections, reflecting their interests, and serving the needs of their own communities. Let’s look at some examples:

Go to Trove and click on ‘tags’ near the top of the page. Here you’ll find a list of the most popular tags added by users to items in Trove.
Look for ‘LRRSA’. What do you think it means? 
A group of enthusiasts have agreed to use a particular tag – something like a controlled vocabulary – to bring together resources that are of interest to them.
Lists are another way that Trove users can create their own collections. They’re simply groups of resources on a particular topic. Here’s a short video describing how to use them:

## Making your own Trove collection (optional)
Following the instructions in the video and the information in the Trove Help Centre, try creating your own list.

Before you start adding items you’ll need to set up your own Trove account:

Click on the ‘Sign up’ button, and follow the instructions. You’ll receive an email to verify your registration.
Once your account is verified, you might need to click on the ‘Login’ button and enter your details.
You’re welcome to create a list on any topic that interests you. If inspiration fails, how about following up on our search example and documenting the amazing history of butter in Australia?

Here are the requirements for your list:

- Add at least 10 items.
- Include at least 2 photos, 2 objects, and 2 newspaper articles.
- Use items with thumbnail images if possible.
- Once you’ve done, go to your list (you can always find your own lists by looking under your User Profile). Click on the ‘List options’ link on the top right of your list and see if you can work out how to select a representative image for your list.

Once you’re done, share a link to your list on Blackboard/Slack.

## From collection to exhibition (optional)

Trove lists are handy, but they don’t look very pretty. There is a way of taking the content of a list (or a series of lists) and turning them into a simple online exhibition.

Here’s an exhibition about [The Chinese in NSW](http://baibi.github.io/chinese-in-nsw-in-pictures/#/) by Kate Bagnall that pulls together content from 10 different lists. Each list provides a different exhibition theme or topic.

It’s easy to turn your list into an exhibition, just follow [these instructions](https://github.com/wragge/diy-trove-exhibition). Have a go and share the results on Blackboard.

Not only is this a nicer way of presenting the contents of your lists, it’s an example of what becomes possible once we share collection data online. We can not only search it, we can build new things with it. 


<font color="blue">
This tutorial was adapted from Tim Sherratt. Original content on this site is licensed under a Creative Commons Attribution 4.0 International License.
</font>